
rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"

postgres:
  container_name: postgres_container
  image: postgres:latest
  environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    PGDATA: /data/postgres
  volumes:
    - postgres:/data/postgres
  ports:
    - "5432:5432"
  restart: unless-stopped